[project]
name = "gigpanel"
version = "1.0.0"
dependencies = [
	"platformdirs",
	"qasync @ git+https://github.com/martinspinler/qasync",
	"aiohttp",
	"midibox[gui]",
	"python-poppler-qt5",
	"pyfluidsynth",
	"pyyaml",
	"PyQtWebEngine",
	"livelist[client] @ git+https://github.com/martinspinler/livelist",
]

[project.optional-dependencies]
box = [
	"numpy",
]

[project.scripts]
gigpanel = "gigpanel.__main__:main"

[tool.setuptools]
packages = ["gigpanel"]

[[tool.mypy.overrides]]
module = "popplerqt5,qasync,midibox.*,mido"
ignore_missing_imports = true
