prefixes:
  cloud: 'cloud/data/'
  docs: 'Documents/'
stores:
  sheets:
    prefix: docs
    path: 'sheets/'
    suffix: '.pdf'
  arrangements:
    prefix: cloud
    path: 'band/scores/'
    pattern: 'band/scores/{name}/{name}{instrument}.pdf'
    suffix: '.pdf'

defaultStore: arrangements
defaultPlaylistClient: mygreatband

playlistClients:
  mygreatband:
    currentBand: 1
    url: 'http://127.0.0.1:8012/band/mygreatband'

midibox:
  default-configuration: midibox
  configurations:
    midibox:
      backend: osc
      backend-params:
        addr: midibox
        port: 4302
    local:
      backend: osc
      backend-params:
        addr: localhost
        port: 4302
    simulator:
      backend: simulator
